export const DOMAINS = [
  'education',
  'agriculture',
  'healthcare',
  'water_resources',
  'environment',
  'energy',
  'urban_development',
  'accessibility',
  'public_administration',
  'rural_livelihoods',
] as const;

export type Domain = (typeof DOMAINS)[number];

export interface DomainDefinition {
  id: Domain;
  labelEn: string;
  labelHi: string;
  description: string;
  keywords: string[];
  keywordsHi: string[];
}

export const DOMAIN_DEFINITIONS: Record<Domain, DomainDefinition> = {
  education: {
    id: 'education',
    labelEn: 'Education & Skilling',
    labelHi: 'शिक्षा एवं कौशल',
    description:
      'Schools, colleges, teachers, students, literacy, dropouts, curriculum, digital learning, vocational training, scholarships, mid-day meals and educational infrastructure.',
    keywords: [
      'school',
      'college',
      'teacher',
      'student',
      'classroom',
      'literacy',
      'dropout',
      'curriculum',
      'exam',
      'scholarship',
      'tuition',
      'library',
      'anganwadi',
      'education',
      'learning',
      'training',
      'skill',
      'vocational',
      'coaching',
      'textbook',
      'enrolment',
      'midday meal',
      'digital learning',
      'e-learning',
      'university',
      'syllabus',
      'tutor',
    ],
    keywordsHi: [
      'स्कूल',
      'विद्यालय',
      'शिक्षक',
      'छात्र',
      'शिक्षा',
      'पढ़ाई',
      'कक्षा',
      'साक्षरता',
      'छात्रवृत्ति',
      'प्रशिक्षण',
      'कौशल',
    ],
  },
  agriculture: {
    id: 'agriculture',
    labelEn: 'Agriculture & Allied',
    labelHi: 'कृषि एवं संबद्ध',
    description:
      'Farming, crops, soil health, irrigation for fields, seeds, fertiliser, pests, livestock, dairy, poultry, fisheries, mandi prices, crop storage and farm mechanisation.',
    keywords: [
      'farm',
      'farmer',
      'crop',
      'soil',
      'seed',
      'fertiliser',
      'fertilizer',
      'pesticide',
      'pest',
      'harvest',
      'paddy',
      'wheat',
      'maize',
      'vegetable',
      'orchard',
      'livestock',
      'cattle',
      'dairy',
      'poultry',
      'fishery',
      'mandi',
      'agriculture',
      'kharif',
      'rabi',
      'tractor',
      'cold storage',
      'yield',
      'horticulture',
      'lac',
      'tasar',
    ],
    keywordsHi: [
      'किसान',
      'खेती',
      'फसल',
      'बीज',
      'खाद',
      'मिट्टी',
      'सिंचाई',
      'पशु',
      'दूध',
      'मंडी',
      'कृषि',
    ],
  },
  healthcare: {
    id: 'healthcare',
    labelEn: 'Healthcare & Nutrition',
    labelHi: 'स्वास्थ्य एवं पोषण',
    description:
      'Hospitals, primary health centres, doctors, nurses, medicines, diagnostics, maternal and child health, malnutrition, immunisation, disease outbreaks, ambulances and telemedicine.',
    keywords: [
      'hospital',
      'clinic',
      'doctor',
      'nurse',
      'medicine',
      'health',
      'patient',
      'disease',
      'malaria',
      'tuberculosis',
      'anaemia',
      'malnutrition',
      'nutrition',
      'vaccine',
      'immunisation',
      'maternal',
      'pregnancy',
      'infant',
      'ambulance',
      'diagnostic',
      'telemedicine',
      'phc',
      'chc',
      'sickle cell',
      'mental health',
      'asha',
      'dispensary',
    ],
    keywordsHi: [
      'अस्पताल',
      'डॉक्टर',
      'दवा',
      'स्वास्थ्य',
      'बीमारी',
      'इलाज',
      'कुपोषण',
      'टीका',
      'एम्बुलेंस',
      'मरीज',
    ],
  },
  water_resources: {
    id: 'water_resources',
    labelEn: 'Water & Sanitation',
    labelHi: 'जल एवं स्वच्छता',
    description:
      'Drinking water supply, handpumps, borewells, groundwater depletion, water quality and contamination, rainwater harvesting, ponds, rivers, toilets, drainage and sewage.',
    keywords: [
      'water',
      'drinking water',
      'handpump',
      'tubewell',
      'borewell',
      'groundwater',
      'well',
      'tap',
      'pipeline',
      'reservoir',
      'pond',
      'river',
      'dam',
      'rainwater',
      'harvesting',
      'contamination',
      'fluoride',
      'arsenic',
      'iron',
      'sanitation',
      'toilet',
      'latrine',
      'sewage',
      'drainage',
      'drain',
      'open defecation',
      'water scarcity',
      'watershed',
    ],
    keywordsHi: [
      'पानी',
      'जल',
      'चापाकल',
      'कुआं',
      'नदी',
      'तालाब',
      'शौचालय',
      'नाली',
      'स्वच्छता',
      'सीवर',
    ],
  },
  environment: {
    id: 'environment',
    labelEn: 'Environment & Forests',
    labelHi: 'पर्यावरण एवं वन',
    description:
      'Air and water pollution, mining impact, deforestation, afforestation, wildlife, biodiversity, solid waste management, plastic waste, climate resilience and land degradation.',
    keywords: [
      'pollution',
      'air quality',
      'smoke',
      'dust',
      'emission',
      'forest',
      'deforestation',
      'tree',
      'afforestation',
      'wildlife',
      'elephant',
      'biodiversity',
      'mining',
      'mine',
      'colliery',
      'coal',
      'coal dust',
      'fly ash',
      'overburden',
      'quarry',
      'waste',
      'garbage',
      'plastic',
      'landfill',
      'recycling',
      'climate',
      'erosion',
      'environment',
      'ecology',
      'contaminated soil',
    ],
    keywordsHi: [
      'प्रदूषण',
      'पर्यावरण',
      'जंगल',
      'वन',
      'पेड़',
      'कचरा',
      'खनन',
      'कोयला',
      'हाथी',
      'जलवायु',
    ],
  },
  energy: {
    id: 'energy',
    labelEn: 'Energy & Electrification',
    labelHi: 'ऊर्जा एवं विद्युतीकरण',
    description:
      'Electricity supply, power cuts, transformers, transmission lines, rural electrification, solar power, micro-grids, cooking fuel, biogas and energy efficiency.',
    keywords: [
      'electricity',
      'power',
      'power cut',
      'load shedding',
      'transformer',
      'grid',
      'transmission',
      'voltage',
      'meter',
      'billing',
      'solar',
      'photovoltaic',
      'microgrid',
      'mini-grid',
      'biogas',
      'lpg',
      'cooking fuel',
      'chulha',
      'street light',
      'generator',
      'electrification',
      'renewable',
      'battery',
      'energy',
    ],
    keywordsHi: [
      'बिजली',
      'विद्युत',
      'ट्रांसफार्मर',
      'सौर',
      'ऊर्जा',
      'कटौती',
      'मीटर',
      'गैस',
      'चूल्हा',
    ],
  },
  urban_development: {
    id: 'urban_development',
    labelEn: 'Urban Development & Infrastructure',
    labelHi: 'शहरी विकास एवं अवसंरचना',
    description:
      'Roads, bridges, traffic, public transport, street lighting, housing, slums, urban flooding, markets, parking and municipal civic infrastructure.',
    keywords: [
      'road',
      'pothole',
      'bridge',
      'culvert',
      'highway',
      'traffic',
      'congestion',
      'parking',
      'bus',
      'transport',
      'footpath',
      'pavement',
      'housing',
      'slum',
      'settlement',
      'urban flooding',
      'waterlogging',
      'municipal',
      'ward',
      'market',
      'encroachment',
      'construction',
      'infrastructure',
      'connectivity',
      'culvert',
    ],
    keywordsHi: ['सड़क', 'पुल', 'यातायात', 'परिवहन', 'बस', 'आवास', 'नगर', 'गड्ढा', 'जलजमाव'],
  },
  accessibility: {
    id: 'accessibility',
    labelEn: 'Accessibility & Inclusion',
    labelHi: 'सुगम्यता एवं समावेशन',
    description:
      'Disability access, ramps, assistive technology, sign language, elderly care, gender inclusion, tribal inclusion, language barriers and access to services for marginalised groups.',
    keywords: [
      'disability',
      'disabled',
      'divyang',
      'wheelchair',
      'ramp',
      'blind',
      'visually impaired',
      'deaf',
      'hearing',
      'sign language',
      'assistive',
      'prosthetic',
      'elderly',
      'senior citizen',
      'accessible toilet',
      'no ramp',
      'wheelchair access',
      'persons with disabilities',
      'inclusion',
      'inclusive',
      'accessible',
      'accessibility',
      'barrier',
      'marginalised',
      'tribal language',
      'santali',
      'braille',
      'special needs',
      'gender',
    ],
    keywordsHi: ['दिव्यांग', 'विकलांग', 'बुजुर्ग', 'समावेशन', 'सुगम्य', 'रैंप', 'बाधा', 'संथाली'],
  },
  public_administration: {
    id: 'public_administration',
    labelEn: 'Public Administration & Service Delivery',
    labelHi: 'लोक प्रशासन एवं सेवा वितरण',
    description:
      'Government service delivery, certificates, ration and PDS, pensions, land records, grievance redressal, corruption, e-governance portals and citizen documentation.',
    keywords: [
      'certificate',
      'ration',
      'pds',
      'ration card',
      'pension',
      'aadhaar',
      'land record',
      'mutation',
      'registry',
      'grievance',
      'complaint',
      'corruption',
      'bribe',
      'delay',
      'panchayat',
      'block office',
      'tehsil',
      'circle office',
      'e-governance',
      'portal',
      'application',
      'subsidy',
      'dbt',
      'beneficiary',
      'documentation',
      'administration',
    ],
    keywordsHi: [
      'प्रमाण पत्र',
      'राशन',
      'पेंशन',
      'भूमि',
      'पंचायत',
      'शिकायत',
      'भ्रष्टाचार',
      'प्रशासन',
      'आवेदन',
      'सब्सिडी',
    ],
  },
  rural_livelihoods: {
    id: 'rural_livelihoods',
    labelEn: 'Rural Livelihoods & Employment',
    labelHi: 'ग्रामीण आजीविका एवं रोजगार',
    description:
      'Employment, MGNREGA, self-help groups, migration and distress migration, handicrafts, forest produce, micro-enterprise, credit access, markets for artisans and cooperatives.',
    keywords: [
      'employment',
      'unemployment',
      'job',
      'livelihood',
      'mgnrega',
      'nrega',
      'wage',
      'migration',
      'migrant',
      'self-help group',
      'shg',
      'sakhi mandal',
      'cooperative',
      'handicraft',
      'artisan',
      'weaver',
      'bamboo',
      'forest produce',
      'mahua',
      'tendu',
      'micro-enterprise',
      'entrepreneur',
      'credit',
      'loan',
      'microfinance',
      'market linkage',
    ],
    keywordsHi: [
      'रोजगार',
      'मजदूरी',
      'पलायन',
      'आजीविका',
      'स्वयं सहायता समूह',
      'मनरेगा',
      'कारीगर',
      'ऋण',
      'बांस',
      'महुआ',
    ],
  },
};

export const DOMAIN_LIST: DomainDefinition[] = DOMAINS.map((d) => DOMAIN_DEFINITIONS[d]);

export function isDomain(value: unknown): value is Domain {
  return typeof value === 'string' && (DOMAINS as readonly string[]).includes(value);
}
