const SYNONYMS: Record<string, string[]> = {
  village: ['gaon', 'gaanv', 'gav', 'gaaon', 'गांव', 'गाँव', 'गाव'],
  broken: ['kharab', 'khrab', 'toota', 'tuta', 'tooti', 'tuti', 'खराब', 'टूटा', 'टूटी'],
  month: ['mahina', 'mahine', 'mahino', 'महीना', 'महीने', 'महीनों'],
  drinking: ['peene', 'पीने'],
  water: ['pani', 'paani', 'jal', 'neer', 'पानी', 'जल', 'नीर'],
  handpump: ['chapakal', 'chapaakal', 'chapanal', 'हैंडपंप', 'चापाकल', 'चापानल'],
  well: [
    'kuan',
    'kuaan',
    'kuwan',
    'inar',
    'inara',
    'chuan',
    'कुआं',
    'कुआँ',
    'इनार',
    'इनारा',
    'चुआं',
  ],
  tap: ['nal', 'नल'],
  toilet: ['shauchalay', 'shauchalaya', 'sauchalay', 'paikhana', 'शौचालय', 'पैखाना'],
  drain: ['nali', 'naali', 'nala', 'naala', 'नाली', 'नाला'],
  pond: ['talab', 'talaab', 'pokhar', 'pokhra', 'तालाब', 'पोखर', 'पोखरा'],
  river: ['nadi', 'नदी'],
  sanitation: ['safai', 'safaai', 'सफाई', 'स्वच्छता'],
  contamination: ['ganda', 'gandaa', 'गंदा', 'गन्दा'],
  electricity: ['bijli', 'bijlee', 'light', 'बिजली', 'विद्युत', 'लाइट'],
  transformer: ['ट्रांसफार्मर', 'ट्रांसफॉर्मर'],
  power: ['katauti', 'कटौती'],
  solar: ['saur', 'सौर'],
  road: ['sadak', 'sarak', 'rasta', 'raasta', 'सड़क', 'रास्ता'],
  pothole: ['gaddha', 'gadda', 'gaddhe', 'gadde', 'गड्ढा', 'गड्ढे', 'गड्डा'],
  bridge: ['pul', 'पुल', 'पुलिया'],
  housing: ['awas', 'aawas', 'makan', 'आवास', 'मकान'],
  school: ['iskool', 'vidyalay', 'vidyalaya', 'pathshala', 'स्कूल', 'विद्यालय', 'पाठशाला'],
  teacher: ['shikshak', 'masterji', 'adhyapak', 'शिक्षक', 'अध्यापक', 'मास्टर'],
  student: ['chhatra', 'छात्र'],
  education: ['shiksha', 'padhai', 'padhaai', 'शिक्षा', 'पढ़ाई'],
  scholarship: ['chhatravritti', 'छात्रवृत्ति'],
  anganwadi: ['aanganbadi', 'anganbadi', 'आंगनबाड़ी', 'आंगनवाड़ी'],
  hospital: ['aspatal', 'aspataal', 'haspatal', 'अस्पताल'],
  doctor: ['daktar', 'doktar', 'डॉक्टर', 'डाक्टर'],
  medicine: ['dawa', 'dawai', 'davai', 'दवा', 'दवाई'],
  disease: ['bimari', 'beemari', 'rog', 'bukhar', 'बीमारी', 'रोग', 'बुखार'],
  patient: ['mariz', 'marij', 'मरीज'],
  health: ['swasthya', 'स्वास्थ्य'],
  malnutrition: ['kuposhan', 'कुपोषण'],
  vaccine: ['tika', 'teeka', 'टीका'],
  ambulance: ['एम्बुलेंस', 'एंबुलेंस'],
  farmer: ['kisan', 'kisaan', 'किसान'],
  farm: ['kheti', 'khet', 'खेती', 'खेत'],
  crop: ['fasal', 'फसल'],
  seed: ['beej', 'बीज'],
  fertiliser: ['khad', 'urea', 'खाद', 'यूरिया'],
  soil: ['mitti', 'मिट्टी'],
  irrigation: ['sinchai', 'सिंचाई'],
  paddy: ['dhan', 'dhaan', 'धान'],
  cattle: ['maveshi', 'pashu', 'मवेशी', 'पशु'],
  dairy: ['doodh', 'dudh', 'दूध'],
  market: ['bazar', 'bazaar', 'बाजार', 'हाट'],
  pollution: ['pradushan', 'प्रदूषण'],
  forest: ['jangal', 'jungle', 'जंगल', 'वन'],
  tree: ['ped', 'पेड़'],
  garbage: ['kachra', 'kachara', 'kooda', 'kuda', 'कचरा', 'कूड़ा'],
  smoke: ['dhuan', 'dhua', 'धुआं', 'धुआँ'],
  dust: ['dhool', 'dhul', 'धूल'],
  mining: ['khanan', 'khadan', 'खनन', 'खदान'],
  coal: ['koyla', 'koyala', 'कोयला'],
  elephant: ['hathi', 'haathi', 'हाथी'],
  ration: ['rashan', 'राशन'],
  pension: ['पेंशन', 'पेन्शन'],
  certificate: ['praman', 'pramaan', 'pramanpatra', 'प्रमाण', 'प्रमाणपत्र'],
  land: ['jameen', 'zameen', 'bhumi', 'जमीन', 'भूमि'],
  bribe: ['ghoos', 'ghus', 'rishwat', 'rishvat', 'घूस', 'रिश्वत'],
  corruption: ['bhrashtachar', 'भ्रष्टाचार'],
  complaint: ['shikayat', 'शिकायत'],
  employment: ['rozgar', 'rojgar', 'naukri', 'naukari', 'रोजगार', 'नौकरी'],
  wage: ['mazdoori', 'majduri', 'majdoori', 'मजदूरी'],
  migration: ['palayan', 'पलायन'],
  loan: ['karz', 'karj', 'rin', 'ऋण', 'कर्ज'],
  mgnrega: ['manrega', 'narega', 'मनरेगा', 'नरेगा'],
  disability: ['viklang', 'विकलांग'],
  divyang: ['दिव्यांग'],
  elderly: ['buzurg', 'bujurg', 'बुजुर्ग'],
};

const FILLER = [
  'hai',
  'hain',
  'ho',
  'tha',
  'thi',
  'ka',
  'ki',
  'ke',
  'ko',
  'mein',
  'mai',
  'main',
  'se',
  'par',
  'aur',
  'ya',
  'ye',
  'yeh',
  'yah',
  'wo',
  'woh',
  'vo',
  'nahi',
  'nahin',
  'nhi',
  'nai',
  'bhi',
  'raha',
  'rahi',
  'rahe',
  'rha',
  'rhi',
  'gaya',
  'gayi',
  'gaye',
  'gya',
  'hua',
  'hui',
  'hue',
  'kar',
  'kr',
  'kiya',
  'kiye',
  'diya',
  'ne',
  'na',
  'hum',
  'ham',
  'hamara',
  'hamare',
  'hamari',
  'humare',
  'mera',
  'meri',
  'mere',
  'apna',
  'apne',
  'bahut',
  'bahot',
  'bohot',
  'kuch',
  'kuchh',
  'koi',
  'sab',
  'abhi',
  'kab',
  'jab',
  'tak',
  'kaise',
  'kya',
  'kyon',
  'kyun',
  'yahan',
  'wahan',
  'wala',
  'wali',
  'liye',
  'paas',
  'unka',
  'unki',
  'iske',
  'uske',
  'log',
  'logon',
  'din',
  'रहा',
  'रही',
  'रहे',
  'गया',
  'गयी',
  'गई',
  'भी',
  'हम',
  'हमारा',
  'हमारे',
  'बहुत',
  'कोई',
  'कुछ',
  'सब',
  'तक',
  'लोग',
  'लोगों',
  'कर',
  'किया',
  'हुआ',
  'हुई',
  'ने',
  'तो',
];

export function foldToken(token: string): string {
  if (/^[a-z]+$/.test(token)) {
    return token
      .replace(/ee/g, 'i')
      .replace(/oo/g, 'u')
      .replace(/w/g, 'v')
      .replace(/ph/g, 'f')
      .replace(/sh/g, 's')
      .replace(/z/g, 'j')
      .replace(/(.)\1+/g, '$1');
  }
  return token.normalize('NFC').replace(/़/g, '').replace(/ँ/g, 'ं');
}

export const CONCEPTS: ReadonlyMap<string, string> = new Map([
  ...Object.entries(SYNONYMS).flatMap(([concept, words]) =>
    words.map((word) => [foldToken(word), concept] as const),
  ),
  ...FILLER.map((word) => [foldToken(word), ''] as const),
]);
